"use client";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import SelectGetComponent from "./SelectGetComponent";
import SubDataContaAdd from "./SubDataContaAdd";

interface ProcedureType {
  id: number;
  name: string;
  step: number;
  pending: number;
  procedureId: number;
  optional: boolean;
  emailCompany: string;
  procedureNumber: number;
  fields: FieldType[];
}

interface FieldType {
  id: number;
  fieldProcessStepId: number;
  order: number;
  name: string;
  initial: string;
  validate: boolean;
  tableDisplay: boolean;
  clientDisplay: boolean;
  lockEdition: boolean;
  type: string;
  label: string;
  unique: boolean;
  url: string;
  allowModification: boolean;
  format: string;
  autoGenerated: boolean;
  color: string;
  fatherFieldId: number | null;
  fatherField: string | null;
  dataSets: any[];
}

let token: string | null = null;

if (typeof window !== "undefined") {
  token = localStorage.getItem("token");
}
const CreateFormCotizacion = ({ idcompany }: { idcompany: number }) => {

  const { data, isLoading, isError, error, refetch } = useQuery<ProcedureType>({
    queryKey: ["procedure", idcompany],
    queryFn: async () => {
      const response = await api.get(
        `processstep/96/procedure/${idcompany}?type=2`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      return response.data;
    },
    enabled: false,
  });

  const [formValues, setFormValues] = useState<{ [key: string]: any }>({});

  useEffect(() => {
 
      refetch();
   
  }, [idcompany, refetch]);

  const handleInputChange = (name: string, value: any) => {
    setFormValues((prevValues) => ({
      ...prevValues,
      [name]: value,
    }));
  };

  const handleSubmit = (event: React.FormEvent) => {
    event.preventDefault();
    console.log(formValues);
  };

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (isError) {
    return <div>Error: {error.message}</div>;
  }

  return (
    <form onSubmit={handleSubmit}>
      {data?.fields.map((field) => (
        <div key={field.id} className="mb-4">
          <label className="block text-sm font-medium text-gray-700">
            {field.label}
          </label>
          {field.type === "text" && (
            <Input
              type="text"
              value={formValues[field.name] || ""}
              onChange={(e) => handleInputChange(field.name, e.target.value)}
            />
          )}
          {field.type === "selectGet" && (
            <SelectGetComponent
              field={field}
              handleInputChange={handleInputChange}
              
            />
          )}
          {field.type === "subDataContaAdd" && (
            <SubDataContaAdd idcompany={idcompany} field={field} handleInputChange={handleInputChange} />
          )}
        </div>
      ))}
      <Button type="submit">Enviar</Button>
    </form>
  );
};


export default CreateFormCotizacion;

